### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by devarshishimpi** [LetsOpen-Source/Support#18]
### Name

Devarshi

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal

**Comment by MrKrishnaAgarwal** [comment]
Hey @devarshishimpi
I will send you invite myself

Before I had a github action, but I didn't want anyone to join.
You can join it.
Sending you 👋

**Comment by devarshishimpi** [comment]
> Hey @devarshishimpi I will send you invite myself
> 
> Before I had a github action, but I didn't want anyone to join. You can join it. Sending you 👋

Okay! Thanks
